version: '3'

networks:
  softel:

services:
  postgres:
    # TypeORM fails with Postgres v.12
    image: postgres:latest
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: softel_subscription
    networks:
      - softel

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6399:6379
  #   command: redis-server
  #   networks:
  #     - softel
