version: '3'

networks:
  softel:

services:
  # postgres:
  #   # TypeORM fails with Postgres v.12
  #   image: postgres:11.5
  #   ports:
  #     - 5455:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: softel_subscription
  #   networks:
  #     - softel

  dynamodb-local:
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'

  redis:
    image: redis:alpine
    ports:
      - 6399:6379
    command: redis-server
    networks:
      - softel
